### ISSUE TITLE
Need more help on extracting Private Key using Frida

### ISSUE THREAD

**Issue by arinc9** [ViRb3/cloudflare-warp-wireguard-client#1]
I set up Frida-server on Android fine and attached to 1.1.1.1 app but the script doesn't really help for someone who's new to Frida and this kind of work at all.

**Comment by dnwk** [comment]
I don't know how to use Frida. But I was able to use VMOS as a virtual machine on Android. It doesn't have Android Keystore. So private key on VMOS is in plaintext.

**Comment by arinc9** [comment]
Yeah, I did the same, with Nox Player.
