### ISSUE TITLE
Warp ios app now provides access to key. Can we use that with this script?

### ISSUE THREAD

**Issue by joshkerr** [ViRb3/cloudflare-warp-wireguard-client#3]
Would it be possible to upgrade the script to use the key displayed in the Cloudflare Warp IOS app?

**Comment by 161134050** [comment]
I don't think the iOS app displays the private keys, you'll have to extract them somehow

**Comment by ViRb3** [comment]
I really doubt that the iOS app provides you with the __private__ keys. Are you sure you are not seeing the __public__ keys? Feel free to re-open with proof and I will gladly take a look at it.
