### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mandofskii** [ViRb3/cloudflare-warp-wireguard-client#5]
Hello can you answer me?
How you found 1.1.1.1 api?
can you give me a tut or only  a description
how you sniff the api url?

**Comment by ViRb3** [comment]
Here's a good start: https://medium.com/@ved_wayal/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29
This isn't something I can provide support for, however, so I am closing this issue.
