### ISSUE TITLE
Generate profile with Cloudflare Warp account Key

### ISSUE THREAD

**Issue by 161134050** [ViRb3/cloudflare-warp-wireguard-client#6]
It seems that Cloudflare have updated their Warp app to 5.0, which includes basic "Account" functionality, all you get is an **account-key**, which I presume Cloudflare uses to generate a wg private key based off this. Right now you can have 5 devices per account-key.

![image](https://user-images.githubusercontent.com/39843740/77225262-864b9700-6ba8-11ea-9230-cfc7ada2577f.png)

They give you the ability to change your key.

**Comment by cpbotha** [comment]
On my iOS 13.3.1 device, version 5.0 20031118000.1 of the CloudFlare 1.1.1.1 app calls this shareable key a "license key".

The license key can be viewed under settings / account. It consists of three dash-separated groups of 8 mixed-case alphanumeric characters each.

**Comment by ViRb3** [comment]
Indeed, this update finally hit my Android phone as well. I will investigate how it works and I will update this project to use this shareable key.

**Comment by cpbotha** [comment]
I have done some further investigation. You can get the `license_key` field from the `account` structure returned by any of the API calls.

I successfully used `wgcf.py` to create a new account, then entered the 8-8-8 license key into my iPhone, then upgraded the account to warp+ unlimited, and now my desktop wireguard is sharing that account.

On the iPhone I can now see the "android" device representing my desktop `wgcf.py` under account / manage devices.

Thanks @ViRb3 for all of your work putting this package together!

**Comment by TheHarryOn** [comment]
> I have done some further investigation. You can get the "license key" from the `license` field in the `account` sub-structure returned by any of the API calls.
> 
> I successfully used `wgcf.py` to create a new account, then entered the 8-8-8 license key into my iPhone, then upgraded the account to warp+ unlimited, and now my desktop wireguard is "automatically" sharing that account.
> 
> On the iPhone I can now see the "android" device representing my desktop `wgcf.py` under account / manage devices.
> 
> Thanks @ViRb3 for all of your work putting this package together!

Sr can you help me, where do I get those API calls, I've tried in the log app and trying capturing packets but I can't see nothing

**Comment by ViRb3** [comment]
This has been implemented in #7, thanks to @perillamint.
